### ISSUE TITLE
Judge for problem 3 is wrong !

### ISSUE THREAD

**Issue by david-ds** [lypnol/graph-theory#3]
La consigne en français dit : 
> Votre algorithme doit retourner le chemin du parcours: liste de noeuds visités en partant et finissant au noeud s.

Cependant si on respecte cette consigne, le juge refuse l'algorithme. 
L'erreur intervient dans la fonction de vérification https://github.com/lypnol/graph-theory/blob/master/problem-03/judge.py#L33 qui n'est pas cohérente avec l'énoncé

**Comment by lypnol** [comment]
Fixed here https://github.com/lypnol/graph-theory/commit/06d07c5bc46dd011f86942ac9d3a163661d887ad
